---
to: package.json
inject: true
before: '"hygen": "'
---
    "@nuxt/typescript-build": "^2.0.2",
    "@nuxtjs/eslint-config": "^3.1.0",
    "@nuxtjs/eslint-module": "^2.0.0",
    "@vue/test-utils": "^1.0.3",
    "babel-core": "7.0.0-bridge.0",
    "babel-eslint": "^10.1.0",
    "babel-jest": "^26.2.2",
    "eslint": "^7.6.0",
    "eslint-config-airbnb": "^18.2.0",
    "eslint-config-prettier": "^6.11.0",
    "eslint-config-standard": "^14.1.1",
    "eslint-friendly-formatter": "^4.0.1",
    "eslint-import-resolver-alias": "^1.1.2",
    "eslint-loader": "^4.0.2",
    "eslint-plugin-import": "^2.22.0",
    "eslint-plugin-jest": "^23.20.0",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-nuxt": ">=1.0.0",
    "eslint-plugin-prettier": "^3.1.4",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-standard": "^4.0.1",
    "eslint-plugin-vue": "^6.2.2",
    "fs": "^0.0.1-security",
    "jest": "^26.2.2",
    "moment": "^2.27.0",
    "node-sass": "^4.14.1",
    "nodemon": "^2.0.4",
    "prettier": "^2.0.5",
    "sass-loader": "^9.0.2",
    "vue-jest": "^3.0.6",
